Repository jenkinsci/jx-resources-plugin, pull requests merged in 2018-12, with the labels that each got.

#6 fix: avoid populating jenkins URLs if using servlerless jenkins
  jx/scripts/README.md
  jx/scripts/release.sh
  src/main/java/org/jenkinsci/plugins/jx/resources/BuildSyncRunListener.java
Labels: size/S

#8 add CI script fix: lets add a release script
  jx/scripts/ci.sh
Labels: size/XS

#9 chore: dummy PR to test CI
  jx/scripts/ci.sh
Labels: approved, size/XS

#12 chore: trigger CD pipeline
  jx/scripts/release.sh
Labels: size/XS

#17 Overrides Jenkins default BUILD_ID and BUILD_NUMBER when running as a…
  src/main/java/org/jenkinsci/plugins/jx/resources/ProwEnvironmentContributor.java
Labels: approved, lgtm, size/S

#18 feat: added ability to expand values of environment variables as build id/numbers
  .gitignore
  src/main/java/org/jenkinsci/plugins/jx/resources/BuildSyncRunListener.java
  src/test/java/org/jenkinsci/plugins/jx/resources/ExpandVarsTest.java
Labels: approved, lgtm, size/M
